# -*- coding: utf-8 -*-
"""Cse422_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y5n_ZGHXd0OL1z-PhdqkU8lvh2aQ5suJ
"""

# Import libraries
import pandas as pd
import numpy as np

dataset = pd.read_csv('/content/flat_price_dataset.csv')

dataset.info()

print("Dataset Shape:", dataset.shape)

print("Keys of dataset:\n", dataset.keys())

dataset['Location'].unique()

dataset['Has_Balcony'].unique()

dataset['Parking_Available'].unique()

dataset['Nearby_Schools'].unique()

dataset['Security_Level'].unique()

dataset['Price_Category'].unique()

#before preprocessing
print("\nMissing values per column:\n")
dataset.isnull().sum()

"""**EDA**"""

import matplotlib.pyplot as plt
outcome_counts = dataset['Price_Category']
fig,ax = plt.subplots()
ax.hist(outcome_counts)
ax.set_title('Class Frequency')
ax.set_xlabel('Price_Category')
ax.set_ylabel('Count')

#class frequency of the output is almost balanced

dataset.head(5)

dataset.hist(figsize=(12,12),bins=20)
plt.show()

"""**Preprocessing**"""

#checking if rows needs to be dropped
dataset['null_count'] = dataset.isnull().sum(axis=1)  # Count nulls per row
rows_with_most_nulls = dataset.sort_values(by='null_count', ascending=False)   # Sorting rows in descending order
rows_with_most_nulls.head(5)

#Since there are a lot of rows with more than 3 null values each we have to fill the null values
dataset.drop('null_count', axis=1, inplace=True)

#to fill up Categorical columns
categorical_cols = ['Location', 'Has_Balcony', 'Parking_Available', 'Nearby_Schools', 'Security_Level', 'Price_Category']
for col in categorical_cols:
    dataset[col].fillna(dataset[col].mode()[0], inplace=True)

#CHECKING
dataset.head(5)

# Checking skewness of all numerical columns
skew_values = dataset.select_dtypes(include=['float64', 'int64']).skew()
print("Skewness of Numerical Features:\n")
print(skew_values.sort_values(ascending=False))

#As all the numerical features are approximately symmetric(skewness close to 0)
#so we are using mean imputation
numerical_cols = ['Distance_to_CityCenter_km', 'Building_Age_Years', 'Num_Bathrooms',
                  'Size_sqft', 'Num_Bedrooms', 'Floor_Number']

for col in numerical_cols:
    dataset[col].fillna(dataset[col].mean(), inplace=True)
# Round only float columns to 2 decimals
float_cols = dataset.select_dtypes(include='float64').columns
dataset[float_cols] = dataset[float_cols].round(2)

print("\nMissing values per column:\n")
dataset.isnull().sum()

dataset.head(10)

#Encoding categorical variables
dataset['Location'] = dataset['Location'].map({'Countryside': 0, 'City Center': 1, 'Suburbs':2 })
dataset['Has_Balcony'] = dataset['Has_Balcony'].map({'Yes': 1, 'No': 0})
dataset['Parking_Available'] = dataset['Parking_Available'].map({'Yes': 1, 'No': 0})
dataset['Nearby_Schools'] = dataset['Nearby_Schools'].map({'Many': 1, 'Few': 0})
dataset['Security_Level'] = dataset['Security_Level'].map({'Low': 0, 'Medium': 1, 'High':2})
dataset['Price_Category'] = dataset['Price_Category'].map({'Low':0, 'Medium': 1, 'High':2})

dataset.head(11)

import seaborn as sns
corr_matrix = dataset.corr()
# Plotting the heatmap for correlation matrix
plt.figure(figsize=(8, 6))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt='.2f', linewidths=3)
plt.show()

#correlations are very close to 0, which means there's no strong linear relationship between any feature and Price_Category
#But correlation only tells us about linear dependence. We can use ML models which might uncover non-linear or combined feature interactions that are important.
#So, we will not remove any coloums yet

#drop coloumns as no realtion with price_category and large number of null values (to increase accuracy)
dataset = dataset.drop(['Nearby_Schools','Num_Bathrooms'], axis = 1)
dataset.shape

# Final check for any missing values
print("\nRemaining missing values:", dataset.isnull().sum().sum())

"""Dataset **splitting**"""

from sklearn.model_selection import train_test_split
# Separate features and target
X = dataset.drop('Price_Category', axis=1)
y = dataset['Price_Category']

# Stratified split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, stratify=y, random_state=42)

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
# Fit on train data and transform both train and test
X_test_scaled = scaler.transform(X_test)

"""**Training** **Models**"""

# models
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier

# Logistic Regression
log_model = LogisticRegression()
log_model.fit(X_train_scaled, y_train)

# Naive Bayes
nb_model = GaussianNB()
nb_model.fit(X_train_scaled, y_train)

#KNN
knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled, y_train)

from sklearn.neural_network import MLPClassifier
# Creating a model with 1 hidden layer of 100 neurons
mlp_model = MLPClassifier(hidden_layer_sizes=(100,), max_iter=500, random_state=42)
mlp_model.fit(X_train_scaled, y_train)

"""**Predictions**"""

# Predictions of each model
y_pred_log = log_model.predict(X_test_scaled)
y_pred_nb = nb_model.predict(X_test_scaled)
y_pred_knn = knn_model.predict(X_test_scaled)
y_pred_mlp = mlp_model.predict(X_test_scaled)

"""**Probabilities**"""

# Probabilities of each model
y_prob_log = log_model.predict_proba(X_test_scaled)
y_prob_nb = nb_model.predict_proba(X_test_scaled)
y_prob_knn = knn_model.predict_proba(X_test_scaled)
y_prob_mlp = mlp_model.predict_proba(X_test_scaled)

# Import metrics
from sklearn.metrics import confusion_matrix, classification_report, precision_score, recall_score, f1_score, roc_auc_score, roc_curve, accuracy_score
import matplotlib.pyplot as plt

# Evaluation function
def evaluate_model(y_true, y_pred, y_prob, model_name):  #predict
    print(f"\nEvaluation for {model_name}")
    print("-" * 40)
    print("Confusion Matrix:\n", confusion_matrix(y_true, y_pred))
    print("\nClassification Report:\n", classification_report(y_true, y_pred))
    # Use 'weighted' average for precision, recall, and F1-score in multiclass problems
    print(f"Accuracy: {accuracy_score(y_true, y_pred):.4f}")
    print(f"Precision: {precision_score(y_true, y_pred, average='weighted'):.4f}")
    print(f"Recall: {recall_score(y_true, y_pred, average='weighted'):.4f}")
    print(f"F1 Score: {f1_score(y_true, y_pred, average='weighted'):.4f}")
    print(f"AUC Score: {roc_auc_score(y_true, y_prob, average='weighted', multi_class='ovr'):.4f}")

# Evaluate Logistic Regression
evaluate_model(y_test, y_pred_log, y_prob_log, "Logistic Regression")

# Evaluate Naive Bayes
evaluate_model(y_test, y_pred_nb, y_prob_nb, "Naive Bayes")

# Evaluate KNN
evaluate_model(y_test, y_pred_knn, y_prob_knn, "KNN")

#Evaluate MLP
evaluate_model(y_test, y_pred_mlp, y_prob_mlp, "Neural Network (MLP)")

from sklearn.preprocessing import label_binarize
from sklearn.metrics import roc_curve, auc
from sklearn.multiclass import OneVsRestClassifier
import matplotlib.pyplot as plt
import numpy as np

# Binarize the output
y_test_binarized = label_binarize(y_test, classes=[0, 1, 2])  # Low=0, Medium=1, High=2
n_classes = y_test_binarized.shape[1]

# Dictionary of model probabilities
models = {
    "Logistic Regression": y_prob_log,
    "Naive Bayes": y_prob_nb,
    "KNN": y_prob_knn,
    "MLP": y_prob_mlp
}

linestyles = {
    "Logistic Regression": '-',
    "Naive Bayes": '-.',
    "KNN": ':',
    "MLP": '--'
}

# Plotting
plt.figure(figsize=(12, 8))

for model_name, y_prob in models.items():
    for i in range(n_classes):
        fpr, tpr, _ = roc_curve(y_test_binarized[:, i], y_prob[:, i])
        roc_auc = auc(fpr, tpr)
        plt.plot(
            fpr, tpr,
            linestyle=linestyles[model_name],
            label=f'{model_name} (Class {i}) AUC = {roc_auc:.2f}'
        )


plt.plot([0, 1], [0, 1], 'k--')
plt.title('Multi-Class ROC & AUC Curve (One-vs-Rest)')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.legend(loc='lower right')
plt.grid()
plt.show()

from sklearn.metrics import accuracy_score
import matplotlib.pyplot as plt

# Calculate accuracies
accuracy_log = accuracy_score(y_test, y_pred_log)
accuracy_nb = accuracy_score(y_test, y_pred_nb)
accuracy_knn = accuracy_score(y_test, y_pred_knn)
accuracy_mlp = accuracy_score(y_test, y_pred_mlp)

# Prepare data
model_names = ['Logistic Regression', 'Naive Bayes', 'KNN', 'Neural Network (MLP)']
accuracies = [accuracy_log, accuracy_nb, accuracy_knn, accuracy_mlp]

# Plotting bar chart
plt.figure(figsize=(8, 6))
bars = plt.bar(model_names, accuracies, color='skyblue')
plt.ylim(0, 1)
plt.ylabel('Accuracy')
plt.title('Model Accuracy Comparison')

# Annotate bars
for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 0.01, f'{yval:.2f}', ha='center')

plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()