# -*- coding: utf-8 -*-
"""21301191_ANONNA_DEV_NIPA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jwK56aIXOxc60Pmz9PC1FGOupAcQAtwu
"""

import pandas as pd
import numpy as np

dataset = pd.read_csv('Heart Disease.csv')

dataset.info()

print("Dataset Shape:", dataset.shape)

print("\nMissing values per column:\n", dataset.isnull().sum())

print("Keys of dataset:\n", dataset.keys())
dataset['Heart Disease (in next 10 years)'].unique()

import matplotlib.pyplot as plt
outcome_counts = dataset['Heart Disease (in next 10 years)']
fig,ax = plt.subplots()
ax.hist(outcome_counts)
ax.set_title('Class Frequency')
ax.set_xlabel('Heart Disease (in next 10 years)')
ax.set_ylabel('Count')

dataset.head()

#Encoding categorical variables ('gender' Male/Female ----> 0/1)
dataset['gender'] = dataset['gender'].map({'Male': 1, 'Female': 0})

dataset.head()

import seaborn as sns

corr_matrix = dataset.corr()

plt.figure(figsize=(20, 15))
sns.heatmap(corr_matrix, cmap='rocket_r', fmt=".2f")
plt.title('Correlation Heatmap')
plt.show()

#drop coloumns as no realtion with heart disease and large number of null values
dataset = dataset.drop(['education','glucose'], axis = 1)
dataset.shape

dataset.isnull().sum()

#filling value in the null value
dataset['heartRate'].fillna(75, inplace=True)

#checking if rows needs to be dropped
dataset['null_count'] = dataset.isnull().sum(axis=1)  # Count nulls per row
rows_with_most_nulls = dataset.sort_values(by='null_count', ascending=False)   # Sorting rows in descending order
rows_with_most_nulls.head(10)

#Since max number of null vales in each row is 2; no need to drop rows
dataset.drop('null_count', axis=1, inplace=True)

#handling missing values
from sklearn.impute import SimpleImputer
impute = SimpleImputer(missing_values=np.nan, strategy='mean')

impute.fit(dataset[['cigsPerDay']])
dataset['cigsPerDay'] = impute.transform(dataset[['cigsPerDay']])

impute.fit(dataset[['BPMeds']])
dataset['BPMeds'] = impute.transform(dataset[['BPMeds']])

impute.fit(dataset[['totChol']])
dataset['totChol'] = impute.transform(dataset[['totChol']])

impute.fit(dataset[['BMI']])
dataset['BMI'] = impute.transform(dataset[['BMI']])

#checking columns for null values
dataset.isnull().sum()

# Final check for any missing values
print("\nRemaining missing values:", dataset.isnull().sum().sum())

#splitting dataset
from sklearn.model_selection import train_test_split

X = dataset.drop('Heart Disease (in next 10 years)', axis=1)
y = dataset['Heart Disease (in next 10 years)']

# Split data: 70% Train, 30% Test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42,
                                                    stratify=y)  # keep proportion of classes
print("Training data shape:", X_train.shape)
print("Test data shape:", X_test.shape)

# Scaling the features as  some models like Logistic Regression work better if features are on the same scale
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

# Fit on train data and transform both train and test
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# models
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

# Logistic Regression
log_model = LogisticRegression()
log_model.fit(X_train_scaled, y_train)

# Random Forest
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(X_train_scaled, y_train)

knn_model = KNeighborsClassifier(n_neighbors=5)
knn_model.fit(X_train_scaled, y_train)

# Predictions
y_pred_log = log_model.predict(X_test_scaled)
y_pred_rf = rf_model.predict(X_test_scaled)
y_pred_knn = knn_model.predict(X_test_scaled)

# Probabilities
y_prob_log = log_model.predict_proba(X_test_scaled)[:, 1]
y_prob_rf = rf_model.predict_proba(X_test_scaled)[:, 1]
y_prob_knn = knn_model.predict_proba(X_test_scaled)[:, 1]

# Import metrics
from sklearn.metrics import confusion_matrix, classification_report, precision_score, recall_score, f1_score, roc_auc_score, roc_curve
import matplotlib.pyplot as plt

# Evaluation function
def evaluate_model(y_true, y_pred, y_prob, model_name):  #predict
    print(f"\nEvaluation for {model_name}")
    print("-" * 40)
    print("Confusion Matrix:\n", confusion_matrix(y_true, y_pred))
    print("\nClassification Report:\n", classification_report(y_true, y_pred))
    print(f"Precision: {precision_score(y_true, y_pred):.4f}")
    print(f"Recall: {recall_score(y_true, y_pred):.4f}")
    print(f"F1 Score: {f1_score(y_true, y_pred):.4f}")
    print(f"AUC Score: {roc_auc_score(y_true, y_prob):.4f}")

# Evaluate Logistic Regression
evaluate_model(y_test, y_pred_log, y_prob_log, "Logistic Regression")

# Evaluate Random Forest
evaluate_model(y_test, y_pred_rf, y_prob_knn, "Random Forest")

# Evaluate KNN
evaluate_model(y_test, y_pred_knn, y_prob_rf, "KNN")

# Plotting ROC Curves
fpr_log, tpr_log, _ = roc_curve(y_test, y_prob_log)
fpr_rf, tpr_rf, _ = roc_curve(y_test, y_prob_rf)
fpr_knn, tpr_knn, _ = roc_curve(y_test, y_prob_knn)

plt.figure(figsize=(10, 6))
plt.plot(fpr_log, tpr_log, label='Logistic Regression (AUC = {:.4f})'.format(roc_auc_score(y_test, y_prob_log)))
plt.plot(fpr_rf, tpr_rf, label='Random Forest (AUC = {:.4f})'.format(roc_auc_score(y_test, y_prob_rf)))
plt.plot(fpr_knn, tpr_knn, label='KNN (AUC = {:.4f})'.format(roc_auc_score(y_test, y_prob_knn)))
plt.plot([0,1], [0,1], 'k--')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curves')
plt.legend()
plt.grid()
plt.show()