# -*- coding: utf-8 -*-
"""21301191_Anonna Dev Nipa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wz8Ef98gAFUkth6vwecn7r7Nz5ZR7cGU
"""

#Problem 1
import math
import random
def alpha_beta_search(depth, is_attacker, alpha, beta, max_value, min_value):
    if depth == 5:
        return calculate_utility_func(max_value, min_value)
    if is_attacker:
        best_score = -math.inf
        for move in range(2):
            score = alpha_beta_search(depth + 1, False, alpha,beta,max_value,min_value)
            best_score = max(best_score, score)
            alpha = max(alpha, best_score)
            if beta<=alpha:  # Prune
                break
        return best_score
    else:
        best_score = math.inf
        for move in range(2):
            score = alpha_beta_search(depth+1,True, alpha, beta, max_value,min_value)
            best_score = min(best_score, score)
            beta = min(beta, best_score)  # Update beta
            if beta<=alpha:  # Prune
                break
        return best_score

def calculate_utility_func(max_value,min_value):
    i = random.choice([0, 1])
    r = random.randint(1, 10) / 10
    result = strength_func(max_value) - strength_func(min_value)+(-1)**i* r
    return result

def strength_func(x):
    return math.log2(x + 1) + (x/10)

def game(first_mover, player1_power, player2_power):
    score_board = {"Carlsen": 0, "Caruana": 0, "Draw": 0}
    for round_num in range(4): # 4 ta game
        if (round_num % 2 == 1 and first_mover == 1) or (round_num % 2 == 0 and first_mover == 0):
            p1 = "Carlsen"
            p2 = "Caruana"
            max_value, min_value = player1_power, player2_power
        else:
            p1 = "Caruana"
            p2 = "Carlsen"
            max_value, min_value = player2_power, player1_power
        final_score =alpha_beta_search(0, True, -math.inf, math.inf,max_value, min_value)  #using alpha-beta search for winner
        if final_score > 0:
            winner = p1
            score_board[winner]+=1
        elif final_score < 0:
            winner = p2
            score_board[winner]+=1
        else:
            winner = "Draw"
            score_board["Draw"]+=1
        # print("--------------------")
        # print(score_board)
        total= round_num+1
        print("Game", total, "Winner:", winner,"(Utility value:", round(final_score, 2),")")
    print("Overall Results:")
    print("Magnus Carlsen Wins:",score_board['Carlsen'])
    print("Fabiano Caruana Wins:",score_board['Caruana'])
    print("Draws:",score_board['Draw'])

    if score_board["Carlsen"]<score_board["Caruana"]:
        print("Overall Winner: Fabiano Caruana")
    elif score_board["Carlsen"]>score_board["Caruana"]:
        print("Overall Winner: Magnus Carlsen")
    else:
        print("Overall Winner: Draw")

#inputs
first_mover = int(input("Enter starting player for game 1 (0 for Carlsen, 1 for Caruana): "))
player1_power = float(input("Enter base strength for Carlsen: "))
player2_power = float(input("Enter base strength for Caruana: "))
game(first_mover, player1_power, player2_power)

#Problem 2
import math
import random
def calculate_utility_func(max_value,min_value):
    i = random.choice([0, 1])
    r = random.randint(1, 10) / 10
    result = strength_func(max_value)-strength_func(min_value)+(-1)**i* r
    return result

def strength_func(x):
    return math.log2(x+ 1) + (x/10)

def simple_minimax(depth, isMaxTurn, max_value,min_value):
    if depth == 5:
        return calculate_utility_func(max_value,min_value)
    if isMaxTurn:
        best_value = -float('inf')
        for i in range(2):  # 2 ta possible moves
            move_value = simple_minimax(depth + 1, False,max_value,min_value)
            best_value = max(best_value, move_value)
        return best_value
    else:
        best_value = float('inf')
        for i in range(2):
            move_value = simple_minimax(depth + 1, True, max_value,min_value)
            best_value = min(best_value, move_value)
        return best_value

def mind_control(max_value,min_value):
    first_choice = calculate_utility_func(max_value,min_value)
    second_choice = calculate_utility_func(max_value,min_value)
    return max(first_choice, second_choice)

starting_player = int(input("Enter who goes first (0 for Light, 1 for L): "))
magic_cost = float(input("Enter the cost of using Mind Control: "))
strength_Light = float(input("Enter base strength for Light: "))
strength_L = float(input("Enter base strength for L: "))

if starting_player == 0:     #agge k jabe assign
    max_value, min_value = strength_Light, strength_L
    max_player_name = "Light"
else:
    max_value, min_value = strength_L, strength_Light
    max_player_name = "L"

normal_game_result = simple_minimax(0, True, max_value, min_value)
mind_control_result = mind_control(max_value, min_value)
final_mind_control_result = mind_control_result - magic_cost  #mind control after incurring the cost

print("Minimax value without Mind Control:", round(normal_game_result, 2))
print("Minimax value with Mind Control:", round(mind_control_result, 2))
print("Minimax value with Mind Control after incurring the cost:", round(final_mind_control_result, 2))

# Decide whether to use Mind Control
if normal_game_result > 0 and mind_control_result > 0 and final_mind_control_result > 0:
    print(max_player_name, "should NOT use Mind Control as the position is already winning.")
elif normal_game_result < 0 and mind_control_result > 0 and final_mind_control_result > 0:
    print(max_player_name, "should use Mind Control.")
elif normal_game_result < 0 and mind_control_result > 0 and final_mind_control_result < 0:
    print(max_player_name, "should NOT use Mind Control as the position is losing either way.")
elif normal_game_result > 0 and mind_control_result > 0 and final_mind_control_result < 0:
    print(max_player_name, "should NOT use Mind Control as it backfires.")