# -*- coding: utf-8 -*-
"""21301191_Anonna Dev Nipa.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ao9pYhxmi3WuHSpRNGOIBSnu2JVHVPQT
"""

#Task 1
import random

def evolution(cap, price, popu, gen):
  pop=[]
  for i in popu:
    if(1<=i["stop_loss"]<=99 and 1<=i["take_profit"]<=99 and 1<=i["trade_size"]<= 99): #jodi value not in range
      pop.append(i)
    else:
      new={"stop_loss": random.randint(1, 99),
            "take_profit": random.randint(1, 99),
            "trade_size": random.randint(1, 99)}
      pop.append(new)

  for i in range(gen):  #sort the population to find the best chromosomes according to fitness value
    for a in range(len(pop)):
      for b in range(a+1,len(pop)):
        if fitness_val(cap, price, pop[a])< fitness_val(cap, price, pop[b]):
          pop[a], pop[b] = pop[b], pop[a]
    # print(pop)
    next_gen = pop[:2] #best two chromosome rakhbo
    while len(next_gen)<len(pop):
      parent1, parent2 = random.sample(pop, 2)  #select two chromosomes randomly from the population to produce offspring
      child1, child2 = crossing(parent1, parent2) #two offspring will be produced
      child1 = mutation(child1)
      child2 = mutation(child2)
      next_gen.append(child1)
      next_gen.append(child2)
    pop = next_gen[:len(pop)]
  best = pop[0]
  # print(best)
  return f"Best_strategy: {best}, Final Profit: {fitness_val(cap, price,best)}"


def fitness_val(cap, price, pop): #fitness function / the total profit
  total=cap
  for cash in price:
    trade_val = total*(pop["trade_size"]/100)
    if cash>= pop['take_profit']:
      total = total+ trade_val*(pop['take_profit']/100)
    elif cash<= -pop["stop_loss"]:
      total = total - trade_val*(pop['stop_loss']/100)
    else:
      total = total + trade_val*(cash/100)
  fitness_score= total-cap
  return fitness_score

def encoding_chromosome(population):
   rep = f"{int(population['stop_loss']):02}{int(population['take_profit']):02}{int(population['trade_size']):02}"
   return rep

def crossing(parent1, parent2):  #single point cross over
  p1_string = encoding_chromosome(parent1)
  p2_string = encoding_chromosome(parent2)
  split_index = random.randint(0,2) # index 0 = stop_loss, 1 = take_profit, 2 = trade_size
  # print(p1_string,p2_string,split_index)
  genes_p1 = [p1_string[:2],p1_string[2:4],p1_string[4:]] #spliting the genes and keeping them in a list
  genes_p2 = [p2_string[:2],p2_string[2:4],p2_string[4:]]
  child1_cross = genes_p1[:split_index] + genes_p2[split_index:]
  child2_cross = genes_p2[:split_index] + genes_p1[split_index:]
  # print(child1_cross)
  # print(child2_cross)
  child1 = "".join(child1_cross) #list to string convert korlam
  child2 = "".join(child2_cross)
  # print(child1)
  child1 = decoding_chromsome(child1)
  child2 = decoding_chromsome(child2)
  return child1, child2

def mutation(pop):
  if random.random()<0.05:
    index = random.choice(["stop_loss","take_profit","trade_size"])
    val = max(1, int(pop[index]*0.05))
    pop[index]= min(99, max(1, pop[index]+ random.choice([-val, val]))) #keeps the value within 99
  return pop
def decoding_chromsome(chromosome):
  return {"stop_loss": int(chromosome[:2]),"take_profit": int(chromosome[2:4]),"trade_size": int(chromosome[4:])  }

#inputs
initial_capital = 1000
historical_prices = [-1.2, 3.4, -0.8, 2.1, -2.5, 1.7, -0.3, 5.8, -1.1, 3.5]
initial_population = [
  {"stop_loss": 2,"take_profit": 5,"trade_size": 20},
  {"stop_loss": 3,"take_profit": 7,"trade_size": 30},
  {"stop_loss": 1.5,"take_profit": 4,"trade_size": 25},
  {"stop_loss": 2.5,"take_profit": 6,"trade_size": 15}]
generations = 10

output = evolution(initial_capital, historical_prices, initial_population, generations)
print(output)

#Task 2
def two_point_crossover(parent1, parent2):
  p1_string= encoding_chromosome(parent1)
  p2_string = encoding_chromosome(parent2)
  print("parent1:", p1_string,"and parent2:", p2_string)
  if len(p1_string)==len(p2_string):
   #indexes to split with
   split1, split2 = sorted(random.sample(range(0, len(p2_string)-1),2)) #making sure 2nd point comes after 1st
  #  print(split1,split2)
   child1_split1 = p1_string[:split1+1] + p2_string[split1+1:]
   child2_split1 = p2_string[:split1+1] + p1_string[split1+1:]
   print(f"After split between index {split1} and {split1+1}: {child1_split1} and {child2_split1}")
   #second split
   child1_split2 = child1_split1[:split2+1] + child2_split1[split2+1:]
   child2_split2= child2_split1[:split2+1] + child1_split1[split2+1:]
   print(f"After split between index {split2} and {split2+1}: {child1_split2} and {child2_split2}")
   return child1_split2, child2_split2


def encoding_chromosome(population):
   rep = f"{int(population['stop_loss']):02}{int(population['take_profit']):02}{int(population['trade_size']):02}"
   return rep
#Input
initial_population= [{"stop_loss": 2, "take_profit": 5, "trade_size": 20},
                     {"stop_loss": 3, "take_profit": 7,"trade_size": 30},
                      {"stop_loss": 1.5, "take_profit": 4, "trade_size": 25},
                    {"stop_loss": 2.5, "take_profit": 6, "trade_size": 15}]
parent1, parent2 = random.sample(initial_population,2)
output = two_point_crossover(parent1, parent2)
print("So the two resultant offsprings are:",output[0], "and", output[1])