# -*- coding: utf-8 -*-
"""21301191_ANONNA DEV NIPA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fyQExd02qvRQJiIbdoySfPIubBgI7HxX
"""

file_handler= open(file = "Input file.txt", mode='r')
file_a = file_handler.read()
#print(file_a)
file_b= file_a.split("\n")

for count in range(len(file_b)):
  file_b[count]= file_b[count].split(" ")
#print(file_b)

table_of_heuristic={}
for counter in range(len(file_b)):
  #print("value",file_b[counter[1]])
  heuristic_er_value= int(file_b[counter][1])
  table_of_heuristic[file_b[counter][0]]= heuristic_er_value #{key:value} = {index0:index1}

print("###############################")
print('Table: ',table_of_heuristic)

graph_of_heuristic={}
in_progress_dict={}

for nums in range(len(file_b)):
  in_progress_dict={}  # temporary dictionary
  for no in range(2, len(file_b), 2):  #starting from second index and increment 2 index por por
     if len(file_b[nums])> no+1: # making sure no er value length theke boro na hoy
       path_er_cost_value = int(file_b[nums][no+1])
       in_progress_dict[file_b[nums][no]]=path_er_cost_value
  #print(in_progress_dict)
  graph_of_heuristic[file_b[nums][0]]=in_progress_dict
print("------------------------------")
print("Graph: ", graph_of_heuristic)

################## A* Search #########################
def a_star_search(shurur_shohor, shesher_shohor):
  rastas= {shurur_shohor: 0} #{visiting cities: f(0)}
  paths_explored={}  #paths gular cities store korbo
  node_cost_track={}  # shurur city to new city cost , g(0)

  for point in graph_of_heuristic:
    node_cost_track[point]= float('inf')
  node_cost_track[shurur_shohor]=0 #starting cityr cost 0
  print("node_cost",node_cost_track)
  #for finding f(0) = g(0) +h(0)
  f_theta_values= {}
  for way in graph_of_heuristic:
     f_theta_values[way] = float('inf')
  f_theta_values[shurur_shohor] = table_of_heuristic[shurur_shohor]  #for shurur city : f(0) = h(0) + 0
  print("f(0): ",f_theta_values)

  while len(rastas)>0: #joto cities ase visit korar
      lowest_f_theta=float('inf')
      shohor = None  #next city to visit with lowest f(0)
      for c in rastas:
        if rastas[c]<lowest_f_theta:
          lowest_f_theta = rastas[c]
          shohor= c
          # print(shohor)
      rastas.pop(shohor)

      # baki neighboring shohor and costs
      pasher_cities = graph_of_heuristic[shohor]
      # print("pasher:",pasher_cities)
      for n in pasher_cities:
        neigh_node_cost = pasher_cities[n] #current city to neighbor city cost
        neigh_all_cost =neigh_node_cost + node_cost_track[shohor]  #total cost
        if neigh_all_cost < node_cost_track[n]:
          paths_explored[n] =shohor
          node_cost_track[n] = neigh_all_cost
          f_theta_values[n]= neigh_all_cost + table_of_heuristic[n]  #updating f(0)
          if n not in rastas:
            rastas[n] = f_theta_values[n]

      if shohor == shesher_shohor: #shesher shohor visit korlam
        choto_rasta =[]  #shortest path store korar list
        while shohor in paths_explored:
          choto_rasta.append(shohor)
          shohor = paths_explored[shohor]
        choto_rasta.append(shurur_shohor)
        print("choto rasta:", choto_rasta)
        output= ""
        for i in range(len(choto_rasta)-1,0, -1):  #reverse list
          output += choto_rasta[i] + " --> "
        output += choto_rasta[0]
        print("# Sample Output:")
        print("Path: " , output)
        print("Total distance: ", node_cost_track[shesher_shohor], 'Km')
        return

  print("NO PATH FOUND")

Start_node = 'Arad'
Destination ='Bucharest'
path = a_star_search(Start_node, Destination)

file_handler.close()