# -*- coding: utf-8 -*-
"""CSE437_Group07.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VvDh7vRyetzPL1v_Vabrne48iicxB-hH
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
import seaborn as sns
from sklearn.decomposition import PCA
from collections import Counter
from scipy.stats import ttest_ind
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC
from sklearn.calibration import CalibratedClassifierCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report, confusion_matrix, ConfusionMatrixDisplay, roc_curve, auc

train_dataset = pd.read_csv('/content/drive/MyDrive/Airline DS/train.csv')
test_dataset = pd.read_csv('/content/drive/MyDrive/Airline DS/test.csv')
train_dataset.info()
test_dataset.info()

train_dataset.shape

test_dataset.shape

print("Keys of train dataset:\n", train_dataset.keys())
train_dataset['satisfaction'].unique()

print("Keys of test dataset:\n", test_dataset.keys())
test_dataset['satisfaction'].unique()

train_dataset.head()

train_dataset.isnull().sum()

test_dataset.isnull().sum()

#assuming that no value in arrival delay means zero minutes delayed
train_dataset['Arrival Delay in Minutes'] = train_dataset['Arrival Delay in Minutes'].fillna(0)
test_dataset['Arrival Delay in Minutes'] = test_dataset['Arrival Delay in Minutes'].fillna(0)

outcome_counts = train_dataset['satisfaction']
fig,ax = plt.subplots()
ax.hist(outcome_counts)
ax.set_title('Class Frequency')
ax.set_xlabel('satisfaction')
ax.set_ylabel('Count')

numerical_data = train_dataset.select_dtypes(include='number')
categorical_data = train_dataset.select_dtypes(include= 'object')

numerical_features = numerical_data.columns.tolist()
categorical_features = categorical_data.columns.tolist()

print(f'Number of numerical features: {len(numerical_features)}')
print(numerical_features)
print(f'Number of categorical features: {len(categorical_features)}')
print(categorical_features)

#categorical unique classes
unique_counts=categorical_data.nunique()
print(unique_counts)

#numerical
unique_counts=numerical_data.nunique()
print(unique_counts)

train_dataset['Gender'].unique()

train_dataset['Customer Type'].unique()

train_dataset['Type of Travel'].unique()

train_dataset['Class'].unique()

train_dataset['satisfaction'].unique()

train_dataset['Gender'] = train_dataset['Gender'].map({'Male': 0, 'Female': 1})
train_dataset['Customer Type'] = train_dataset['Customer Type'].map({'disloyal Customer': 0, 'Loyal Customer': 1})
train_dataset['Type of Travel'] = train_dataset['Type of Travel'].map({'Personal Travel': 0, 'Business travel': 1})
train_dataset['Class'] = train_dataset['Class'].map({'Eco Plus': 0, 'Business': 1, 'Eco': 2})
train_dataset['satisfaction'] = train_dataset['satisfaction'].map({'neutral or dissatisfied': 0, 'satisfied': 1})

test_dataset['Gender'] = test_dataset['Gender'].map({'Male': 0, 'Female': 1})
test_dataset['Customer Type'] = test_dataset['Customer Type'].map({'disloyal Customer': 0, 'Loyal Customer': 1})
test_dataset['Type of Travel'] = test_dataset['Type of Travel'].map({'Personal Travel': 0, 'Business travel': 1})
test_dataset['Class'] = test_dataset['Class'].map({'Eco Plus': 0, 'Business': 1, 'Eco': 2})
test_dataset['satisfaction'] = test_dataset['satisfaction'].map({'neutral or dissatisfied': 0, 'satisfied': 1})

train_dataset.head()

numerical_data.hist(figsize=(12,12),bins=20)
plt.show()

numerical_data['Seat comfort'].hist(bins=20)
plt.title('Seat comfort Distribution')
plt.xlabel('Seat comfort')
plt.ylabel('Frequency')
plt.show()

for col in categorical_features:
    plt.figure(figsize=(8, 4))
    plt.title(f'Distribution of {col}')
    categorical_data[col].value_counts().sort_index().plot(kind='bar', rot=0, xlabel=col,ylabel='count')
    plt.tight_layout()
    plt.show()

corr_matrix = train_dataset.corr()

plt.figure(figsize=(20, 15))
sns.heatmap(corr_matrix, annot= True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap')
plt.show()

"""# Principal component analysis"""

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(train_dataset)
X_test_scaled = scaler.transform(test_dataset)

pca = PCA(n_components=0.95)
X_scaled = X_train_scaled
X_pca = pca.fit_transform(X_scaled)

print(f"Original shape: {X_scaled.shape}")
print(f"PCA shape: {X_pca.shape}")

plt.figure(figsize=(8, 4))
plt.plot(range(1, len(pca.explained_variance_ratio_)+1), pca.explained_variance_ratio_, marker='o')
plt.title('Explained Variance by Each Principal Component')
plt.xlabel('Principal Component')
plt.ylabel('Explained Variance Ratio')
plt.grid(True)
plt.show()

loadings = pca.components_  # shape: (n_components, n_features)
feature_names = train_dataset.columns
loading_df = pd.DataFrame(loadings.T, columns=[f'PC{i+1}' for i in range(pca.n_components_)],index=feature_names)

# Top contributing features for each PC
for i in range(pca.n_components_):
    print(f"\nTop features for PC{i+1}:")
    print(loading_df[f'PC{i+1}'].abs().sort_values(ascending=False).head(5))

top_features = []
#top 5 features for each principal component
for i in range(pca.n_components_):
    top = loading_df[f'PC{i+1}'].abs().sort_values(ascending=False).head(5)
    top_features.extend(top.index.tolist())

feature_frequency = Counter(top_features)

pca_feature_counts = pd.DataFrame.from_dict(feature_frequency, orient='index', columns=['Frequency'])
pca_feature_counts = pca_feature_counts.sort_values(by='Frequency', ascending=False)
print(pca_feature_counts)

"""# **T** **test**"""

satisfied = train_dataset[train_dataset['satisfaction'] == 1]['Gate location']
dissatisfied = train_dataset[train_dataset['satisfaction'] == 0]['Gate location']

t_stat, p_val = ttest_ind(satisfied, dissatisfied, equal_var=False)
print("T-test for Gate Location vs Satisfaction")
print(f"p-value = {p_val:.4f}")

satisfied = train_dataset[train_dataset['satisfaction'] == 1]['Departure/Arrival time convenient']
dissatisfied = train_dataset[train_dataset['satisfaction'] == 0]['Departure/Arrival time convenient']

t_stat, p_val = ttest_ind(satisfied, dissatisfied, equal_var=False)

print("T-test for Departure/Arrival Time Convenient vs Satisfaction")
print(f"p-value = {p_val:.4f}")

# Departure Delay
satisfied_dep = train_dataset[train_dataset['satisfaction'] == 1]['Departure Delay in Minutes']
dissatisfied_dep = train_dataset[train_dataset['satisfaction'] == 0]['Departure Delay in Minutes']

t_stat_dep, p_val_dep = ttest_ind(satisfied_dep, dissatisfied_dep, equal_var=False)
print("T-test for Departure Delay in Minutes vs Satisfaction")
print(f"p-value = {p_val_dep:.4f}")

# Arrival Delay
satisfied_arr = train_dataset[train_dataset['satisfaction'] == 1]['Arrival Delay in Minutes']
dissatisfied_arr = train_dataset[train_dataset['satisfaction'] == 0]['Arrival Delay in Minutes']

t_stat_arr, p_val_arr = ttest_ind(satisfied_arr, dissatisfied_arr, equal_var=False)
print("\nT-test for Arrival Delay in Minutes vs Satisfaction")
print(f"p-value = {p_val_arr:.4f}")

train_dataset = train_dataset.drop(['Unnamed: 0', 'id', 'Gender', 'Gate location'], axis=1)
test_dataset = test_dataset.drop(['Unnamed: 0', 'id', 'Gender', 'Gate location'], axis=1)

corr_matrix = train_dataset.corr()

plt.figure(figsize=(20, 15))
sns.heatmap(corr_matrix, annot= True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Heatmap')
plt.show()

"""**Train test set**"""

X_train = train_dataset.drop('satisfaction', axis=1)
Y_train = train_dataset['satisfaction']

X_test = test_dataset.drop('satisfaction', axis=1)
Y_test = test_dataset['satisfaction']

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

"""# KNN"""

knn = KNeighborsClassifier(n_neighbors=5)

knn.fit(X_train_scaled, Y_train)
y_pred = knn.predict(X_test_scaled)

cm = confusion_matrix(Y_test, y_pred)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
fig, ax = plt.subplots(figsize=(8, 6))
disp.plot(cmap='Blues', ax=ax, values_format=',')
plt.title("Confusion Matrix for KNN")
plt.show()

class_report = classification_report(Y_test, y_pred)
print("Classification Report of KNN:")
print(class_report)

y_prob_knn = knn.predict_proba(X_test_scaled)[:, 1]

accuracy_knn = accuracy_score(Y_test, y_pred)
print(f"Accuracy: {accuracy_knn:.4f}")
print(f"Precision: {precision_score(Y_test, y_pred, average='weighted'):.4f}")
print(f"Recall: {recall_score(Y_test, y_pred, average='weighted'):.4f}")
print(f"F1 Score: {f1_score(Y_test, y_pred, average='weighted'):.4f}")

"""# Random Forest

"""

rf = RandomForestClassifier(n_estimators=100, random_state=42)

rf.fit(X_train_scaled, Y_train)

y_pred_rf = rf.predict(X_test_scaled)

cm = confusion_matrix(Y_test, y_pred_rf)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
fig, ax = plt.subplots(figsize=(8, 6))
disp.plot(cmap='Blues', ax=ax, values_format=',')
plt.title("Confusion Matrix for Random Forest")
plt.show()

class_report_rf = classification_report(Y_test, y_pred_rf)
print("Classification Report of Random Forest:")
print(class_report_rf)

y_prob_rf = rf.predict_proba(X_test_scaled)[:, 1]
accuracy_rf = accuracy_score(Y_test, y_pred_rf)
print(f"Accuracy: {accuracy_rf:.4f}")
print(f"Precision: {precision_score(Y_test, y_pred_rf, average='weighted'):.4f}")
print(f"Recall: {recall_score(Y_test, y_pred_rf, average='weighted'):.4f}")
print(f"F1 Score: {f1_score(Y_test, y_pred_rf, average='weighted'):.4f}")

"""# Decision Tree"""

dt = DecisionTreeClassifier()

dt.fit(X_train_scaled, Y_train)

dt_preds = dt.predict(X_test_scaled)

cm = confusion_matrix(Y_test, dt_preds)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
fig, ax = plt.subplots(figsize=(8, 6))
disp.plot(cmap='Blues', ax=ax, values_format=',')
plt.title("Confusion Matrix of Decision Tree")
plt.show()

class_report = classification_report(Y_test, dt_preds)
print("Classification Report for Decision Tree:")
print(class_report)

y_prob_dt = dt.predict_proba(X_test_scaled)[:, 1]
accuracy_dt = accuracy_score(Y_test, dt_preds)
print(f"Accuracy: {accuracy_dt:.4f}")
print(f"Precision: {precision_score(Y_test, dt_preds, average='weighted'):.4f}")
print(f"Recall: {recall_score(Y_test, dt_preds, average='weighted'):.4f}")
print(f"F1 Score: {f1_score(Y_test, dt_preds, average='weighted'):.4f}")

"""# SVM"""

base_svm = LinearSVC(max_iter=10000, random_state=42)
svm = CalibratedClassifierCV(base_svm)

svm.fit(X_train_scaled, Y_train)

y_pred_svm = svm.predict(X_test_scaled)

cm = confusion_matrix(Y_test, y_pred_svm)
disp = ConfusionMatrixDisplay(confusion_matrix=cm)
fig, ax = plt.subplots(figsize=(8, 6))
disp.plot(cmap='Blues', ax=ax, values_format=',')
plt.title("Confusion Matrix for SVM")
plt.show()

class_report_svm = classification_report(Y_test, y_pred_svm)
print("Classification Report of SVM:")
print(class_report_svm)

y_prob_svm = svm.predict_proba(X_test_scaled)[:, 1]
accuracy_svm = accuracy_score(Y_test, y_pred_svm)
print(f"Accuracy: {accuracy_svm:.4f}")
print(f"Precision: {precision_score(Y_test, y_pred_svm, average='weighted'):.4f}")
print(f"Recall: {recall_score(Y_test, y_pred_svm, average='weighted'):.4f}")
print(f"F1 Score: {f1_score(Y_test, y_pred_svm, average='weighted'):.4f}")

"""# Performance Comparison"""

model_names = ['KNN','Random Forest','SVM', 'Decision Tree']
accuracies = [accuracy_knn,accuracy_rf,accuracy_svm,accuracy_dt]

plt.figure(figsize=(8, 6))
bars = plt.bar(model_names, accuracies, color='skyblue')
plt.ylim(0, 1)
plt.ylabel('Accuracy')
plt.title('Model Accuracy Comparison')

for bar in bars:
    yval = bar.get_height()
    plt.text(bar.get_x() + bar.get_width()/2, yval + 0.01, f'{yval:.2f}', ha='center')

plt.tight_layout()
plt.show()

prec_knn = precision_score(Y_test, y_pred, average=None)
prec_rf = precision_score(Y_test, y_pred_rf, average=None)
prec_svm = precision_score(Y_test, y_pred_svm, average=None)
prec_dt = precision_score(Y_test, dt_preds, average=None)

precisions = np.array([prec_knn, prec_rf, prec_svm, prec_dt])
labels = ['KNN', 'Random Forest', 'SVM', 'Decision Tree']
x = np.arange(len(labels))
width = 0.35

plt.figure(figsize=(10, 6))
bar1 = plt.bar(x - width/2, precisions[:, 0], width, label='Class 0', color='skyblue')
bar2 = plt.bar(x + width/2, precisions[:, 1], width, label='Class 1', color='steelblue')
for bars in [bar1, bar2]:
    for bar in bars:
        yval = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2, yval + 0.01, f'{yval:.2f}', ha='center')

plt.xlabel('Model')
plt.ylabel('Precision Score')
plt.title('Precision per Class for Each Model')
plt.xticks(x, labels)
plt.ylim(0, 1.1)
plt.legend()
plt.tight_layout()
plt.show()

recall_knn = recall_score(Y_test, y_pred, average=None)
recall_rf = recall_score(Y_test, y_pred_rf, average=None)
recall_svm = recall_score(Y_test, y_pred_svm, average=None)
recall_dt = recall_score(Y_test, dt_preds, average=None)

recalls = np.array([recall_knn, recall_rf, recall_svm, recall_dt])
labels = ['KNN', 'Random Forest', 'SVM', 'Decision Tree']
x = np.arange(len(labels))
width = 0.35

plt.figure(figsize=(10, 6))
bar1 = plt.bar(x - width/2, recalls[:, 0], width, label='Class 0', color='steelblue')
bar2 = plt.bar(x + width/2, recalls[:, 1], width, label='Class 1', color='skyblue')

for bars in [bar1, bar2]:
    for bar in bars:
        yval = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2, yval + 0.01, f'{yval:.2f}', ha='center')

plt.xlabel('Model')
plt.ylabel('Recall Score')
plt.title('Recall per Class for Each Model')
plt.xticks(x, labels)
plt.ylim(0, 1.1)
plt.legend()
plt.tight_layout()
plt.show()

f1_knn = f1_score(Y_test, y_pred, average=None)
f1_rf = f1_score(Y_test, y_pred_rf, average=None)
f1_svm = f1_score(Y_test, y_pred_svm, average=None)
f1_dt = f1_score(Y_test, dt_preds, average=None)

f1s = np.array([f1_knn, f1_rf, f1_svm, f1_dt])
x = np.arange(len(labels))
width = 0.35

plt.figure(figsize=(10, 6))
bar1 = plt.bar(x - width/2, f1s[:, 0], width, label='Class 0', color='darkcyan')
bar2 = plt.bar(x + width/2, f1s[:, 1], width, label='Class 1', color='skyblue')

for bars in [bar1, bar2]:
    for bar in bars:
        yval = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2, yval + 0.01, f'{yval:.2f}', ha='center')

plt.xlabel('Model')
plt.ylabel('F1 Score')
plt.title('F1 Score per Class for Each Model')
plt.xticks(x, labels)
plt.ylim(0, 1.1)
plt.legend()
plt.tight_layout()
plt.show()

fpr_knn, tpr_knn, _ = roc_curve(Y_test, y_prob_knn)
roc_auc_knn = auc(fpr_knn, tpr_knn)

fpr_rf, tpr_rf, _ = roc_curve(Y_test, rf.predict_proba(X_test_scaled)[:, 1])
roc_auc_rf = auc(fpr_rf, tpr_rf)

fpr_dt, tpr_dt, _ = roc_curve(Y_test, y_prob_dt)
roc_auc_dt = auc(fpr_dt, tpr_dt)

fpr_svm, tpr_svm, _ = roc_curve(Y_test, y_prob_svm)
roc_auc_svm = auc(fpr_svm, tpr_svm)

plt.figure(figsize=(10, 8))
plt.plot(fpr_knn, tpr_knn, label=f'KNN (AUC = {roc_auc_knn:.2f})')
plt.plot(fpr_rf, tpr_rf, label=f'Random Forest (AUC = {roc_auc_rf:.2f})')
plt.plot(fpr_dt, tpr_dt, label=f'Decision Tree (AUC = {roc_auc_dt:.2f})')
plt.plot(fpr_svm, tpr_svm, label=f'SVM (AUC = {roc_auc_svm:.2f})')

plt.plot([0, 1], [0, 1], 'k--', label='Random Guess')
plt.xlabel('False Positive Rate')
plt.ylabel('True Positive Rate')
plt.title('ROC Curve Comparison')
ticks = np.arange(0.1, 1.2, 0.1)
plt.xticks(ticks)
plt.yticks(ticks)
plt.legend(loc='lower right')
plt.grid(True)
plt.show()

